### PR TITLE
Revert "Additions to Basic Python Syntax"

### PR DESCRIPTION
**Pull request by maaslalani**
Reverts maaslalani/Codev#15

### CODE REVIEW

**Comment by kabollinger** [comment]
@Chiouonthis Do you have any idea why this broke the website? @maaslalani can you give us some detail on the issue so that we can help you fix the formatting problem without having to completely remove the work that you asked for?

**Comment by Chiouonthis** [comment]
@kabollinger I don't. I'm not sure how the inclusion of text to a Markdown file would break a website; that doesn't seem likely? What do you mean by the site being broken?

**Comment by kabollinger** [comment]
@Chiouonthis I agree that your change shouldn't have broken the site. I actually have no idea what is meant by "broken site". I swear that when I wrote that comment, the description of this PR included a reasoning that the additions "broke the site," so we would have to ask @maaslalani. 

@maaslalani what was the pressing problem with the previous PR that caused it to have to be reverted? What can we do to fix it and give you the content you desire?

**Comment by Chiouonthis** [comment]
@kabollinger I saw that same comment in the PR, something about formatting? Again, not sure how a single .md could break a whole site. I think that I'm probably done contributing to this project, as the experience hasn't been very good. Good luck.

**Comment by kabollinger** [comment]
@Chiouonthis Oh. So I'm not crazy... yeah, then I'm right there with you. I have enough of a skeleton that I can PR for Hacktober and not feel bad, but I will not continue with this experience. Thank you and good luck.

**Pull request merged**
